fix(sks): module error when keycloak is disabled
camptocamp/devops-stack pull request #774
Opened 2021-09-10 08:55 UTC by ckaenzig

The keycloak_admin_password output can't be set when keycloak is disabled
because the kubernetes secret doesn't exist.

This solution doesn't rely on whether the secret exists or not, but on whether
keycloak is disabled in the app_of_apps_overrides variable. The only drawback
I see is that this condition will have to be changed if the default value for
apps.keycloak.enabled is ever changed (in modules/values.tmpl.yaml).

This PR replaces #768

2021-09-10 08:57 UTC, mcanevet approved these changes

2021-09-10 08:59 UTC, mcanevet requested changes
Maybe you should also do it on other variants that are exposing this output (k3s and cce IIRC)

2021-09-10 09:06 UTC, ckaenzig commented
Darn it, yamldecode fails with an empty string (default value of the `app_of_apps_override` variable). More work is needed :disappointed:

2021-09-10 09:07 UTC, mcanevet commented
Maybe we could default to `---` or use `coalesce()`

2022-07-01 09:50 UTC, ckaenzig commented
Closing this PR because it's not needed in any current project anymore, and not relevant to the next modular version.

2022-07-01 09:50 UTC, closed without merging