Reconfigure loki
camptocamp/devops-stack pull request #922
Opened 2022-07-19 14:29 UTC by modridi

2022-11-22 14:38 UTC, fsismondi requested changes

2022-11-22 14:38 UTC, fsismondi commented on argocd/loki-distributed/values.yaml
> +    resources:
```suggestion
    #resources:
```

2022-11-28 08:54 UTC, fsismondi commented
@modridi I successfully tested this PR last week, I pushed some fixes directly to the PR.
 
I think we need a few fixes before we release this:
1. frontendIngress for Loki should be optional (sth like a loki-distributed.fromendIngress.enabled)
2. "letsencrypt-staging" -> "letsencrypt-prod"

I wont have time this week to include these changes, could you?

2022-12-29 21:41 UTC, modridi commented
Feature will be available in modular version.

2022-12-29 21:41 UTC, closed without merging